version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 12
  ignore:
  - dependency-name: vue-demi
    versions:
    - 0.6.1
    - 0.6.2
    - 0.7.1
    - 0.7.2
    - 0.7.3
    - 0.7.4
  - dependency-name: y18n
    versions:
    - 4.0.1
