name: CI

on:
  push:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.15.1
      - name: Intall
        run: yarn install --frozen-lockfile
      - name: Check format
        run: yarn format:check
      - name: Test
        run: yarn test
      - name: Build
        run: yarn build
