name: CI

on: push

jobs:
  lint:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 10.16.3
          registry-url: 'https://registry.npmjs.org'
      - name: intall
        run: yarn install --frozen-lockfile
      - name: lint
        run: yarn lint
      - name: test
        run: yarn test
      - name: build
        run: yarn build
